package com.example.hrms.Mernis;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.12.6.0
//
// Created by Quasar Development 
//
//----------------------------------------------------



public interface DVBIServiceEvents
{
    void Starting();
    void Completed(DVBOperationResult result);
}
