package com.example.hrms.Mernis;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.12.6.0
//
// Created by Quasar Development 
//
//----------------------------------------------------



public class DVBOperationResult< T>
{
    
    public java.lang.Exception Exception;
    
    public T Result;
    
    public java.lang.Object Tag;
    
    public java.lang.String MethodName;
}
